---
title: "Ikea R final proj Quarto"
format: html
editor: visual
execute: 
  eval: false
  echo: false
---

Package read-in and here::here

```{r}
library(tidyverse)
library(gtsummary)
library(here)
ikea <- read.csv(here::here("ikea.csv"))
```

GT Summary table

```{r}
tbl_summary(
	ikea,
	by = sellable_online,
	include = c(category, other_colors),
label = list(
	category ~"Furniture Category",
	other_colors ~"Other Colors Sold"
))
```

Regression Table

```{r}
tbl_uvregression(
	ikea,
	y = price,
	include = c(category, sellable_online, other_colors, height, depth, width),
	method = lm,
	label = list(
		category ~"Furniture Category",
		other_colors ~"Other Colors Sold",
		sellable_online ~"Sellable Online",
  	height ~"Height in cm",
  	depth ~"Depth in cm",
  	width ~"Width in cm"),
) |>
	bold_labels()
```

Data figure: Basic histogram with custom titles and labels

```{r}
hist(ikea$width,
		 main = "Distribution of IKEA Furniture Width",  # Title of the histogram
		 xlab = "Width (in cm)",                         # X-axis label
		 ylab = "Frequency",                             # Y-axis label
		 col = "#1E90FF",                                   # Color of the bars
		 border = "black")                               # Color of the bar borders
```
